Repository Nexters/Boolti, pull requests merged in 2024-03, with the labels that each got.

#182 Feature/boolti 181 탈퇴 후 30일 이내 재로그인 시 다이얼로그 표시
  data/src/main/java/com/nexters/boolti/data/network/response/LoginResponse.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/model/LoginUserState.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#183 Refactor/internal data layer에 접근 제한자 추가
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/DeviceTokenDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/HostDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/PolicyDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/RemoteConfigDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/ReservationDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/ShowDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/SignUpDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/TicketDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/TicketingDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/TokenDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/UserDataSource.kt
  data/src/main/java/com/nexters/boolti/data/db/AppSettings.kt
  data/src/main/java/com/nexters/boolti/data/db/DataStore.kt
  data/src/main/java/com/nexters/boolti/data/di/DataSourceModule.kt
  data/src/main/java/com/nexters/boolti/data/di/FirebaseModule.kt
  data/src/main/java/com/nexters/boolti/data/di/NetworkModule.kt
  data/src/main/java/com/nexters/boolti/data/di/RepositoryModule.kt
  data/src/main/java/com/nexters/boolti/data/network/AuthAuthenticator.kt
  data/src/main/java/com/nexters/boolti/data/network/AuthInterceptor.kt
  data/src/main/java/com/nexters/boolti/data/network/api/DeviceTokenService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/HostService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/LoginService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/ReservationService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/ShowService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/SignUpService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/TicketService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/TicketingService.kt
  data/src/main/java/com/nexters/boolti/data/network/api/UserService.kt
  data/src/main/java/com/nexters/boolti/data/network/request/DeviceTokenRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/request/RefreshRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/request/ReservationInviteTicketRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/request/ReservationSalesTicketRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/response/CheckInviteCodeResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/DeviceTokenResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/HostedShowDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ImageResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/LoginResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ManagerCodeDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDetailResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/SalesTicketTypesDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ShowDetailResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ShowResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/SignUpResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/TicketDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/TicketingInfoDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/UserResponse.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/ConfigRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/HostRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/ReservationRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/ShowRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/TicketRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/repository/TicketingRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/usecase/IsLoggedInUseCase.kt
Labels: refactor

#187 feat : 코루틴 익셉션 핸들러 추가
  presentation/src/main/java/com/nexters/boolti/presentation/QrScanViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/base/BaseViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/HomeViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingViewModel.kt
Labels: bug

#194 Boolti-190 feat: 공연 등록 메뉴 추가
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#198 fix : 이미지 상세로 내비게이션시 발생하는 크래시 수정
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
Labels: bug

#184 Feature/navigation 내비게이션 리팩토링 (잘 돌아가는 코드는 건드는 거 아니랬는데... 건드렸다...)
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainDestination.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailContentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailContentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowImagesNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowImagesScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
Labels: refactor

#199 fix : 빈공간 생기는 문제 해결
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
Labels: bug

#200 189 : 사업자 정보 추가
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtAppBar.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/BusinessInformation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainDestination.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/business/BusinessNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/business/BusinessScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#206 Feature/201 환불 flow 수정사항
  data/src/main/java/com/nexters/boolti/data/repository/ReservationRepositoryImpl.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtCheckBox.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/BankSelection.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/ReasonPage.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundInfoPage.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat, refactor
