Repository Nexters/Boolti, pull requests merged in 2024-04, with the labels that each got.

#208 Feature/boolti 193
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDetailResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/TicketDto.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ReservationDetail.kt
  domain/src/main/java/com/nexters/boolti/domain/model/Ticket.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/HorizontalStepper.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/MainButton.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/ShowFeed.kt
  presentation/src/main/java/com/nexters/boolti/presentation/extension/LocalDateTime.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/AccountTransferContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/TicketSummarySection.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingConfirmDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingViewModel.kt
  presentation/src/main/res/drawable/ic_stepper_minus.xml
  presentation/src/main/res/drawable/ic_stepper_plus.xml
  presentation/src/main/res/values/strings.xml
Labels: feat, style

#205 Feature/191 딥링크
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/AuthAuthenticator.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/nexters/boolti/presentation/screen/DeepLinkEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/HomeViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/splash/SplashActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/splash/SplashViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/service/BtFirebaseMessagingService.kt
  presentation/src/main/java/com/nexters/boolti/presentation/service/BtNotification.kt
  presentation/src/main/res/drawable/ic_logo.xml
Labels: feat

#213 Fix/212 3차 디자인 QA 반영
  data/src/main/java/com/nexters/boolti/data/repository/TicketingRepositoryImpl.kt
  presentation/src/main/java/com/nexters/boolti/presentation/extension/ReservationState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/business/BusinessScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/AccountTransferContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/TicketSummarySection.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/drawable/ic_logo.xml
  presentation/src/main/res/values/strings.xml
Labels: bug, style

#214 Release/1.4.0
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingConfirmDialog.kt
Labels: bug, enhancement, style

#211 fallback url 설정
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
Labels: feat

#216 Fix/boolti 215 QA 2차 수정
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtAppBar.kt
  presentation/src/main/java/com/nexters/boolti/presentation/extension/NavController.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/business/BusinessScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentToolbar.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrScanScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailContentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowImagesScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
Labels: bug, enhancement, style

#219 Fix/boolti 217
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
Labels: bug, style

#233 Kotest를 이용한 자동 테스트
  .github/workflows/pull-request-ci.yml
  .gitignore
  build.gradle.kts
  domain/build.gradle.kts
  domain/src/test/java/com/nexters/boolti/domain/KotestConfig.kt
  domain/src/test/java/com/nexters/boolti/domain/model/ShowTest.kt
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
Labels: chore

#234 Feature/boolti 192 토스 페이먼츠 결제 연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  data/src/main/java/com/nexters/boolti/data/datasource/TicketingDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/TicketingService.kt
  data/src/main/java/com/nexters/boolti/data/network/request/ReservationSalesTicketRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ApprovePaymentResponse.kt
  data/src/main/java/com/nexters/boolti/data/network/response/OrderIdDto.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDetailResponse.kt
  data/src/main/java/com/nexters/boolti/data/repository/TicketingRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ApprovePaymentResponse.kt
  domain/src/main/java/com/nexters/boolti/domain/model/Currency.kt
  domain/src/main/java/com/nexters/boolti/domain/model/PaymentType.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ReservationDetail.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/TicketingRepository.kt
  domain/src/main/java/com/nexters/boolti/domain/request/OrderIdRequest.kt
  domain/src/main/java/com/nexters/boolti/domain/request/PaymentApproveRequest.kt
  domain/src/main/java/com/nexters/boolti/domain/request/TicketingRequest.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/extension/String.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainDestination.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/AccountTransferContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingConfirmDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Theme.kt
  presentation/src/main/res/values/strings.xml
  settings.gradle.kts
  tosspayments/.gitignore
  tosspayments/build.gradle.kts
  tosspayments/consumer-rules.pro
  tosspayments/proguard-rules.pro
  tosspayments/src/androidTest/java/com/nexters/boolti/tosspayments/ExampleInstrumentedTest.kt
  tosspayments/src/main/AndroidManifest.xml
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/BTDialog.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/PaymentEvent.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentWidgetActivity.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentsWidgetViewModel.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/extension/Currency.kt
  tosspayments/src/main/res/drawable-v24/selector_rounded_cta.xml
  tosspayments/src/main/res/drawable/selector_rounded_cta.xml
  tosspayments/src/main/res/font/pretendard_semi_bold.otf
  tosspayments/src/main/res/layout/activity_toss_payment_widget.xml
  tosspayments/src/main/res/layout/dialog_common.xml
  tosspayments/src/main/res/values/colors.xml
  tosspayments/src/main/res/values/strings.xml
  tosspayments/src/main/res/values/styles.xml
  tosspayments/src/main/res/values/themes.xml
  tosspayments/src/test/java/com/nexters/boolti/tosspayments/ExampleUnitTest.kt
Labels: chore, feat
