Repository Nexters/Boolti, pull requests merged in 2024-02, with the labels that each got.

#132 fix : 의도치 않은 refresh 호출 방어
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailViewModel.kt
Labels: bug

#135 Boolti-134 feat: Ticket 에 ticketNotice 필드 추가
  data/src/main/java/com/nexters/boolti/data/network/response/TicketDto.kt
  domain/src/main/java/com/nexters/boolti/domain/model/Ticket.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
Labels: feat

#138 디자인 QA 반영
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/CopyButton.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Type.kt
  presentation/src/main/res/values/strings.xml
Labels: bug

#139 Qa/boolti 136 디자인 수정
  presentation/src/main/java/com/nexters/boolti/presentation/component/MainButton.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/AccountTransferContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketEmptyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Dimen.kt
Labels: style

#141 Feature/boolti 140 입력 창 요구사항 반영
  presentation/src/main/java/com/nexters/boolti/presentation/component/BTTextField.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/ManagerCodeDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
Labels: enhancement

#144 QA: 디자인 검수 2차
  domain/src/main/java/com/nexters/boolti/domain/model/Ticket.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/BTDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/AccountTransferContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrScanScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/ManagerCodeDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: style

#147 QA 내용 수정 2차
  data/src/main/java/com/nexters/boolti/data/network/response/ShowDetailResponse.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ShowDetail.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
Labels: style

#149 Feature/boolti 148 티켓 상세 문구 및 스낵바 배경 디자인 수정
  presentation/src/main/java/com/nexters/boolti/presentation/component/ToastSnackbarHost.kt
  presentation/src/main/res/values/strings.xml
Labels: style

#152 QA 3차
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtCircularProgressIndicator.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrScanScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailContentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Type.kt
  presentation/src/main/res/font/sb_aggro_b.otf
  presentation/src/main/res/font/sb_aggro_m.otf
Labels: bug, feat

#157 Boolti-156 fix: QR 조건 개선
  domain/src/main/java/com/nexters/boolti/domain/model/Ticket.kt
Labels: bug

#160 Fix/159 홈 스크롤 모션 수정 이제 완벽해~~
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
Labels: enhancement

#161 Boolti-155 style: QR 디자인 개선
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/res/drawable/ic_logo_boolti.xml
Labels: style

#163 Feature/boolti 162 회원 탈퇴
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/UserDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/UserService.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  domain/src/main/java/com/nexters/boolti/domain/request/SignoutRequest.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutNotice.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutReason.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#164 66 / zoomable 추가
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowImagesScreen.kt
Labels: feat

#168 Feature/boolti 165 로딩, 간격 수정 등 스타일 작업
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketViewModel.kt
Labels: style

#169 Boolti-166 feat: QR 스캔 토스트 수정 반영
  presentation/src/main/java/com/nexters/boolti/presentation/QrScanActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/QrScanViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/CircleBgIcon.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/ToastSnackbarHost.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrScanScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Color.kt
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_error.xml
  presentation/src/main/res/drawable/ic_warning.xml
Labels: style

#170 Feature/boolti 167 예매 시 확인 다이얼로그 표시
  presentation/src/main/java/com/nexters/boolti/presentation/extension/String.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingConfirmDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/VisualTransformation.kt
  presentation/src/main/res/values/strings.xml
Labels: feat, style

#173 Boolti-172 style: 티켓 목록 포스터 scale type 변경
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
Labels: style

#178 Feature/175 폰트 세부사항 조정
  presentation/src/main/java/com/nexters/boolti/presentation/component/ShowFeed.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Type.kt
  presentation/src/main/res/font/sb_aggro_b.otf
Labels: enhancement

#177 Feature/176 snackbar 보일러 플레이트 코드 개선
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/SnackbarController.kt
Labels: enhancement

#179 Feature/171 QA 및 디자인 수정 4차
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDetailResponse.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ReservationDetail.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/ShowFeed.kt
  presentation/src/main/java/com/nexters/boolti/presentation/constants/ShowConstants.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/SwipeableImage.kt
  presentation/src/main/res/values/strings.xml
Labels: enhancement

#174 Feature/154 푸시 알림
  app/src/main/AndroidManifest.xml
  data/build.gradle.kts
  data/src/main/java/com/nexters/boolti/data/datasource/DeviceTokenDataSource.kt
  data/src/main/java/com/nexters/boolti/data/datasource/TokenDataSource.kt
  data/src/main/java/com/nexters/boolti/data/di/NetworkModule.kt
  data/src/main/java/com/nexters/boolti/data/network/api/DeviceTokenService.kt
  data/src/main/java/com/nexters/boolti/data/network/request/DeviceTokenRequest.kt
  data/src/main/java/com/nexters/boolti/data/network/response/DeviceTokenResponse.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/nexters/boolti/presentation/extension/Activity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/extension/Context.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/HomeViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/service/BtFirebaseMessagingService.kt
  presentation/src/main/res/values/strings.xml
Labels: feat
