Repository Nexters/Boolti, pull requests merged in 2024-10, with the labels that each got.

#303 302 카드 선택 기능 부활
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/CardSelection.kt
Labels: feat

#311 fix : 이미지 통짜로 변경
  data/src/main/java/com/nexters/boolti/data/datasource/GiftDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/GiftService.kt
  data/src/main/java/com/nexters/boolti/data/network/response/GiftImageResponse.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/DummyDatas.kt
  presentation/src/main/java/com/nexters/boolti/presentation/reservationdetail/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/CardSelection.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/GiftScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/giftcomplete/GiftCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/Indicator.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowImagesScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/SwipeableImage.kt
  presentation/src/main/res/values/strings.xml
Labels: style

#315 314 : 선물 카드 추가 QA
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/CardSelection.kt
Labels: bug

#307 Feature/300 인앱 웹뷰 환경에서 공연 등록하기
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/model/TokenPair.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainDestination.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/giftcomplete/GiftCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/BtWebChromeClient.kt
Labels: feat

#316 Boolti-312 style: BtAppBar 패딩 값 수정
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtAppBar.kt
Labels: style

#310 Boolti-309 fix: 토스 페이먼츠 OrderName 인코딩 버그 패치
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentWidgetActivity.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/extension/String.kt
Labels: bug
