Repository Nexters/Boolti, pull requests merged in 2024-05, with the labels that each got.

#239 Boolti-238 feat: 결제 관련 약관 노션 연결 및 동의 로직 개선
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingState.kt
Labels: enhancement, feat

#236 Feature/223 환불 flow 교체
  data/src/main/java/com/nexters/boolti/data/datasource/TicketingDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/TicketingService.kt
  data/src/main/java/com/nexters/boolti/data/network/response/ReservationDetailResponse.kt
  data/src/main/java/com/nexters/boolti/data/repository/TicketingRepositoryImpl.kt
  data/src/main/java/com/nexters/boolti/data/util/MapperExtensions.kt
  domain/src/main/java/com/nexters/boolti/domain/model/ReservationDetail.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/TicketingRepository.kt
  domain/src/main/java/com/nexters/boolti/domain/request/PaymentCancelRequest.kt
  presentation/src/main/java/com/nexters/boolti/presentation/extension/PaymentType.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundInfoPage.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#244 리드미 수정
  README.md
Labels: documentation

#242 Boolti-227 feat: 구매 중 품절 케이스 구현
  data/src/main/java/com/nexters/boolti/data/datasource/TicketingDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/TicketingService.kt
  data/src/main/java/com/nexters/boolti/data/repository/TicketingRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/exception/TicketingException.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/PaymentFailureDialog.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/SalesTicketViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/res/values/strings.xml
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/PaymentEvent.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentWidgetActivity.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentsWidgetViewModel.kt
  tosspayments/src/main/res/layout/dialog_common.xml
  tosspayments/src/main/res/values/strings.xml
Labels: feat

#245 Feature/boolti 241 티켓 UI 버그 수정
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketContent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketScreen.kt
Labels: bug, enhancement, feat, style

#251 Feature/250 링크 하이라이팅
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailContentScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/UrlParser.kt
  presentation/src/test/java/com/nexters/boolti/presentation/ExampleUnitTest.kt
  presentation/src/test/java/com/nexters/boolti/presentation/util/UrlParserTest.kt
Labels: feat
