Repository Nexters/Boolti, pull requests merged in 2024-08, with the labels that each got.

#278 Fix/277 유저 정보 관련 안정화 작업
  data/src/main/java/com/nexters/boolti/data/datasource/UserDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/UserService.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  domain/src/main/java/com/nexters/boolti/domain/usecase/GetUserUsecase.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/GiftViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: bug

#280 Boolti-279 chore: 화면 이동 시 로그 추적
  data/src/main/java/com/nexters/boolti/data/datasource/AuthDataSource.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/rememberNavControllerWithLog.kt
Labels: chore

#284 Feature/283 티켓 보기 버튼 구현
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentNavigation.kt
Labels: feat

#286 Feature/285 홈 화면 배너 추가
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/res/drawable/background_banner.jpg
  presentation/src/main/res/drawable/fire.png
Labels: feat
