Repository Nexters/Boolti, pull requests merged in 2024-11, with the labels that each got.

#324 317 공연 공유 텍스트 변경
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailScreen.kt
  presentation/src/main/res/values/strings.xml
Labels: style

#328 Boolti-320 feat: 식별코드 선택 시 복사
  presentation/src/main/java/com/nexters/boolti/presentation/screen/accountsetting/AccountSettingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/ClipboardUtil.kt
  presentation/src/main/res/values/strings.xml
Labels: feat

#326 Boolti-319 feat: 토스페이먼츠 상품명 수정
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/GiftScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/TossPaymentWidgetActivity.kt
  tosspayments/src/main/java/com/nexters/boolti/tosspayments/extension/String.kt
Labels: feat

#330 Boolti-329 feat: 공통 웹뷰 커스텀뷰 작성 및 User-Agent 추가
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtWebView.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/PolicyBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/BtWebChromeClient.kt
Labels: refactor

#342 Feature/341 받은 선물 취소하기
  data/src/main/java/com/nexters/boolti/data/datasource/GiftDataSource.kt
  data/src/main/java/com/nexters/boolti/data/network/api/GiftService.kt
  data/src/main/java/com/nexters/boolti/data/network/response/TicketGroupDto.kt
  data/src/main/java/com/nexters/boolti/data/repository/GiftRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/model/Ticket.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/GiftRepository.kt
  gradle/libs.versions.toml
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailEvent.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailUiState.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailViewModel.kt
  presentation/src/main/res/values/strings.xml
Labels: feat
