Repository Nexters/Boolti, pull requests merged in 2025-01, with the labels that each got.

#313 Refactor/253 Navigation 2.8.x Safe Args 적용
  domain/src/main/java/com/nexters/boolti/domain/model/Sns.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/extension/NavController.kt
  presentation/src/main/java/com/nexters/boolti/presentation/reservationdetail/ReservationDetailNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainDestination.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/accountsetting/AccountSettingNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/business/BusinessNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/GiftNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/giftcomplete/GiftCompleteNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/link/LinkListNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/link/LinkListScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/link/LinkListViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/navigation/HomeRoute.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/navigation/MainRoute.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/navigation/ProfileRoute.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/navigation/ShowRoute.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/navigation/TicketRoute.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/payment/PaymentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/perforemdshows/PerformedShowsNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/perforemdshows/PerformedShowsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/perforemdshows/PerformedShowsViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profile/ProfileNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profile/ProfileViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/link/LinkEditViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/link/ProfileLinkEditNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/profile/ProfileEditNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/sns/ProfileSnsEditNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/sns/SnsEditViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/report/ReportViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailContentNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowImagesNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/rememberNavControllerWithLog.kt
Labels: refactor

#358 Feature/boolti 347 웹뷰 브릿지 연결 (공연 등록)
  data/src/main/java/com/nexters/boolti/data/datasource/AuthTokenDataSource.kt
  data/src/main/java/com/nexters/boolti/data/di/DataSourceModule.kt
  data/src/main/java/com/nexters/boolti/data/di/NetworkModule.kt
  data/src/main/java/com/nexters/boolti/data/network/AuthAuthenticator.kt
  data/src/main/java/com/nexters/boolti/data/repository/AuthRepositoryImpl.kt
  domain/src/main/java/com/nexters/boolti/domain/model/TokenPairs.kt
  domain/src/main/java/com/nexters/boolti/domain/repository/AuthRepository.kt
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtWebView.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showregistration/ShowRegistrationViewModel.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/SnackbarController.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/bridge/BridgeCallbackHandler.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/bridge/BridgeDto.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/bridge/BridgeManager.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/bridge/CommandType.kt
Labels: feat

#357 Feature/boolti 343 edge to edge 활성화 및 스타일 반영
  presentation/src/main/java/com/nexters/boolti/presentation/QrScanActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/BtAppBar.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/GradientBackground.kt
  presentation/src/main/java/com/nexters/boolti/presentation/component/StatusBarCover.kt
  presentation/src/main/java/com/nexters/boolti/presentation/reservationdetail/ReservationDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/Main.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/MainActivity.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/gift/GiftScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/giftcomplete/GiftCompleteScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/home/HomeScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/link/LinkListScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/login/LoginScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/my/MyNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/perforemdshows/PerformedShowsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/link/LinkEditScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/profile/ProfileEditScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/sns/SnsEditScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/HostedShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrFullScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/qr/QrScanScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/ReasonPage.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundInfoPage.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/refund/RefundScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/reservations/ReservationsScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/show/ShowScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailButtons.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/showdetail/ShowDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutReason.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/signout/SignoutScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/TicketNavigation.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticket/detail/TicketDetailScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/ChooseTicketBottomSheet.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/ticketing/TicketingScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Dimen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/theme/Theme.kt
  presentation/src/main/java/com/nexters/boolti/presentation/util/TicketShape.kt
Labels: style

#362 Feature/boolti 355 프로필 섬네일 UI 변경
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profile/ProfileScreen.kt
  presentation/src/main/res/drawable/ic_profile_placeholder.png
Labels: style

#364 Boolti-339 프로필 편집 - 링크, SNS 목록 순서 변경
  gradle/libs.versions.toml
  presentation/build.gradle.kts
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/profile/ProfileEditScreen.kt
  presentation/src/main/java/com/nexters/boolti/presentation/screen/profileedit/profile/ProfileEditViewModel.kt
  presentation/src/main/res/drawable/ic_reordable_handle.xml
  presentation/src/main/res/values/strings.xml
Labels: feat
